### ISSUE TITLE
ubuntu 16.04 EOL'ed, minor cleanup

### ISSUE THREAD

**Issue by truatpasteurdotfr** [jenniening/deltaVinaXGB#5]
Hi 

Ubuntu LTS 16.04 is EOL for public updates, switching the base to 18.04 in the Dockerfile is trivial and seems to work fine.
ref: https://wiki.ubuntu.com/Releases 

One can also delete the downloaded files once the tarball/zip files are expanded.

Finally making a pre-built docker image available from dockerhub would also expand your user base!

Cheers

Tru

**Comment by jenniening** [comment]
Hi, thanks for the suggestion. So the issue you commented in another thread is already solved, right? Just want to confirm.

**Comment by truatpasteurdotfr** [comment]
no I have the same issue for ubuntu 18.04 an 16.04:
```
FileNotFoundError: [Errno 2] No such file or directory: 'score_v1.txt'
```

**Comment by jenniening** [comment]
I answer you question in the other thread, so I will close this one. Thanks!
