### ISSUE TITLE
issue with running the test command: "python run_DXGB.py --help"

### ISSUE THREAD

**Issue by Sinsilcobio** [jenniening/deltaVinaXGB#7]
Hello Jenniening,

I installed all the packages and dependencies according to the procedure mentioned in the "readme.md" file.
However, when I tried to run the first test command, the following error popped up. 

Could you please give me a clue what I am missing?

Thank you,
Sajjad

(DXGB) sajads-air:DXGB sajadahrari$ conda activate DXGB
(DXGB) sajads-air:DXGB sajadahrari$ python run_DXGB.py --help
Traceback (most recent call last):
  File "run_DXGB.py", line 6, in <module>
    from DXGB.convert_file import RF20_main as RF20_main
ModuleNotFoundError: No module named 'DXGB'

**Comment by jenniening** [comment]
HI, did you run 'python setup.py install' ? Also, when you run 'python run_DXGB.py --help', could you check if you are in deltaVInaXGB package?

**Comment by Sinsilcobio** [comment]
Hi Jenniening,

I re-run the "python setup.py install". 

The issue was resolved yet the following error popped up (I have numbered it as error number 1) which seems to be related to "Open Babel" installation.

I tried to reinstall "Open Babel with "conda install -c openbabel openbabel" command and error number 2 showed up (which seems to be related to packaging incompatibility).

I am installing it on my Mac and was wondering if it is the source of the issue?

Thank you,
Sajjad

**Error 1**

(DXGB) sajads-air:DXGB sajadahrari$ conda activate DXGB
(DXGB) sajads-air:DXGB sajadahrari$ python run_DXGB.py --help
Traceback (most recent call last):
  File "run_DXGB.py", line 7, in <module>
    from DXGB.run_features import run_features as run_features
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/sajadahrari/opt/anaconda3/lib/python3.8/site-packages/DXGB-0.1.0-py3.8.egg/DXGB/run_features.py", line 16, in <module>
    import DXGB.cal_sasa
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/sajadahrari/opt/anaconda3/lib/python3.8/site-packages/DXGB-0.1.0-py3.8.egg/DXGB/cal_sasa.py", line 7, in <module>
    from DXGB.featureSASA import sasa
  File "<frozen zipimport>", line 259, in load_module
  File "/Users/sajadahrari/opt/anaconda3/lib/python3.8/site-packages/DXGB-0.1.0-py3.8.egg/DXGB/featureSASA.py", line 4, in <module>
    import os, sys, pybel
ModuleNotFoundError: No module named 'pybel'

==========================================================================================
**Error 2**

(DXGB) sajads-air:DXGB sajadahrari$ conda install -c openbabel openbabel
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                          -                                                        /  

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package blis conflicts for:
libblas -> blis[version='0.5.1.*|>=0.5.2,<0.5.3.0a0|>=0.6.0,<0.6.1.0a0|>=0.6.1,<0.6.2.0a0|>=0.7.0,<0.7.1.0a0|>=0.8.0,<0.8.1.0a0|>=0.8.1,<0.8.2.0a0']
libcblas -> libblas==3.9.0=11_osx64_blis -> blis[version='0.5.1.*|>=0.5.2,<0.5.3.0a0|>=0.6.0,<0.6.1.0a0|>=0.6.1,<0.6.2.0a0|>=0.7.0,<0.7.1.0a0|>=0.8.0,<0.8.1.0a0|>=0.8.1,<0.8.2.0a0']
liblapack -> libblas=3.9.0 -> blis[version='0.5.1.*|>=0.5.2,<0.5.3.0a0|>=0.6.0,<0.6.1.0a0|>=0.6.1,<0.6.2.0a0|>=0.7.0,<0.7.1.0a0|>=0.8.0,<0.8.1.0a0|>=0.8.1,<0.8.2.0a0']
numpy -> libblas[version='>=3.8.0,<4.0a0'] -> blis[version='0.5.1.*|>=0.5.2,<0.5.3.0a0|>=0.6.0,<0.6.1.0a0|>=0.6.1,<0.6.2.0a0|>=0.7.0,<0.7.1.0a0|>=0.8.0,<0.8.1.0a0|>=0.8.1,<0.8.2.0a0']
scipy -> libblas[version='>=3.8.0,<4.0a0'] -> blis[version='0.5.1.*|>=0.5.2,<0.5.3.0a0|>=0.6.0,<0.6.1.0a0|>=0.6.1,<0.6.2.0a0|>=0.7.0,<0.7.1.0a0|>=0.8.0,<0.8.1.0a0|>=0.8.1,<0.8.2.0a0']

Package numpy conflicts for:
py-xgboost -> numpy
py-xgboost -> scikit-learn -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.17.5,<2.0a0|>=1.18.5,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.19.2,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.18.1,<2.0a0|>=1.11|>=1.15.1,<2.0a0']
scikit-learn -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.17.5,<2.0a0|>=1.18.5,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.19.2,<2.0a0|>=1.9.3,<2.0a0|>=1.9']
numpy
scipy -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.17.5,<2.0a0|>=1.18.5,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.19.2,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.15.1,<2.0a0']
xgboost=0.80.0 -> numpy
scikit-learn -> scipy -> numpy[version='>=1.11|>=1.18.1,<2.0a0|>=1.15.1,<2.0a0']
xgboost=0.80.0 -> scipy -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.17.5,<2.0a0|>=1.18.5,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.19.2,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.15.1,<2.0a0']

Package llvm-openmp conflicts for:
libopenblas -> llvm-openmp[version='>=10.0.0|>=10.0.1|>=11.0.0|>=11.1.0|>=12.0.1|>=9.0.1|>=9.0.0']
libblas -> libopenblas[version='>=0.3.17,<0.3.18.0a0'] -> llvm-openmp[version='>=10.0.0|>=10.0.1|>=11.0.0|>=11.1.0|>=12.0.1|>=8.0.0|>=8.0.1|>=9.0.1|>=9.0.0']
xgboost=0.80.0 -> py-xgboost==0.80=py36h0a44026_1001 -> llvm-openmp[version='8.0.0|8.0.0|8.0.1|>=4.0.1',build='h770b8ee_1|h770b8ee_0|h770b8ee_0']
llvm-openmp
liblapack -> libgfortran5[version='>=9.3.0'] -> llvm-openmp[version='>=10.0.1|>=8.0.0|>=8.0.1']
libopenblas -> libgfortran5[version='>=9.3.0'] -> llvm-openmp[version='>=8.0.0|>=8.0.1']
py-xgboost -> libxgboost==1.4.0=he49afe7_0 -> llvm-openmp[version='>=10.0.1|>=11.0.0|>=11.0.1|>=11.1.0|>=12.0.1|>=9.0.1']
libcblas -> libgfortran5[version='>=9.3.0'] -> llvm-openmp[version='>=10.0.1|>=8.0.0|>=8.0.1']
scikit-learn -> llvm-openmp[version='>=10.0.0|>=10.0.1|>=11.0.0|>=11.0.1|>=11.1.0|>=12.0.1|>=9.0.1|>=9.0.0']
numpy -> openblas[version='>=0.2.15'] -> llvm-openmp[version='>=10.0.0|>=10.0.1|>=11.0.0|>=11.1.0|>=12.0.1|>=9.0.1|>=9.0.0']
libgfortran -> libgfortran5 -> llvm-openmp[version='>=10.0.1']
py-xgboost -> llvm-openmp[version='>=10.0.0|>=4.0.1|>=9.0.0|>=8.0.1']
libgfortran -> llvm-openmp[version='>=8.0.0|>=8.0.1']
libxgboost -> llvm-openmp[version='>=10.0.0|>=10.0.1|>=11.0.0|>=11.0.1|>=11.1.0|>=9.0.1|>=9.0.0|>=4.0.1|>=8.0.1']
libgfortran5 -> llvm-openmp[version='>=10.0.1|>=8.0.0']
scipy -> libgfortran5[version='>=9.3.0'] -> llvm-openmp[version='>=10.0.0|>=10.0.1|>=8.0.0|>=8.0.1|>=11.1.0|>=12.0.1|>=11.0.0|>=9.0.1|>=9.0.0']

Package ca-certificates conflicts for:
openbabel -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
scikit-learn -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
joblib -> python -> ca-certificates
pip -> python -> ca-certificates
scipy -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
setuptools -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
xgboost=0.80.0 -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
python_abi -> python=2.7 -> ca-certificates
ca-certificates
py-xgboost -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
numpy -> python[version='>=2.7,<2.8.0a0'] -> ca-certificates
openssl -> ca-certificates
wheel -> python[version='!=3.0,!=3.1,!=3.2,!=3.3,!=3.4'] -> ca-certificates
python=3.7 -> openssl[version='>=1.1.1j,<1.1.2a'] -> ca-certificates

Package readline conflicts for:
python_abi -> python=3.9 -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0|7.*|7.0.*']
scipy -> python[version='>=3.7,<3.8.0a0'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0|7.*|7.0.*']
py-xgboost -> python[version='>=3.7,<3.8.0a0'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0|7.*|7.0.*']
joblib -> python[version='>=3.6'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0|7.*|7.0.*']
python=3.7 -> readline[version='>=7.0,<8.0a0|>=8.0,<9.0a0']
wheel -> python[version='!=3.0,!=3.1,!=3.2,!=3.3,!=3.4'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0|7.0.*|7.*']
pip -> python[version='>=3.6'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0|7.*|7.0.*']
threadpoolctl -> python[version='>=3.6'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0|7.*']
openbabel -> python[version='>=3.7,<3.8.0a0'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|7.*|7.0.*|>=8.1,<9.0a0']
readline
setuptools -> python[version='>=3.8,<3.9.0a0'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|7.*|>=8.1,<9.0a0|7.0.*']
numpy -> python[version='>=3.7,<3.8.0a0'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0|7.*|7.0.*']
sqlite -> readline[version='6.2.*|7.0|7.0.*|>=7.0,<8.0a0|>=8.0,<9.0a0|>=8.1,<9.0a0']
python=3.7 -> sqlite[version='>=3.34.0,<4.0a0'] -> readline[version='>=8.1,<9.0a0']
scikit-learn -> python[version='>=3.7,<3.8.0a0'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|7.*|>=8.1,<9.0a0|7.0.*']
xgboost=0.80.0 -> python[version='>=3.6,<3.7.0a0'] -> readline[version='6.2.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0|7.*|7.0.*']

Package ncurses conflicts for:
wheel -> python[version='!=3.0,!=3.1,!=3.2,!=3.3,!=3.4'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
scikit-learn -> pypy3.7[version='>=7.3.5'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']
xgboost=0.80.0 -> python[version='>=3.6,<3.7.0a0'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
sqlite -> ncurses[version='5.9|5.9.*|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']
python=3.7 -> ncurses[version='>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']
python_abi -> python=3.9 -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
sqlite -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='6.0.*|>=6.0,<7.0a0|>=6.1,<7.0a0']
numpy -> pypy3.7[version='>=7.3.5'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']
scipy -> pypy3.7[version='>=7.3.5'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']
setuptools -> python[version='>=3.8,<3.9.0a0'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0']
joblib -> python[version='>=3.6'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
py-xgboost -> pypy3.7[version='>=7.3.4'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']
readline -> ncurses[version='5.9.*|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0|>=6.0,<7.0a0|6.0.*']
openbabel -> python[version='>=3.7,<3.8.0a0'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.1,<7.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0']
pip -> python[version='>=3.6'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
python=3.7 -> readline[version='>=8.0,<9.0a0'] -> ncurses[version='5.9.*|>=6.1,<6.3.0a0|>=6.0,<7.0a0|6.0.*']
threadpoolctl -> python[version='>=3.6'] -> ncurses[version='>=6.0,<7.0a0|>=6.1,<6.3.0a0|>=6.2,<6.3.0a0|>=6.2,<7.0a0|>=6.1,<7.0a0']
ncurses

Package scipy conflicts for:
scikit-learn -> scipy[version='>=0.19.1']
xgboost=0.80.0 -> scipy
py-xgboost -> scikit-learn -> scipy[version='>=0.19.1']
py-xgboost -> scipy
scipy
....

**Comment by jenniening** [comment]
Thanks for the update! Could you try 'pip install openbabel' to install openbable?

**Comment by Sinsilcobio** [comment]
Thank you very much for your reply.

I tried to install with pip. However, the following list of errors showed up.

It seems that openbabel has already been installed with anaconda3 as I can see it running by typing "obabel" in the terminal.

Could you please give me a clue what I am missing?
Thank you


(DXGB) sajads-air:DXGB sajadahrari$ pip install openbabel
Collecting openbabel
  Using cached openbabel-3.1.1.1.tar.gz (82 kB)
Building wheels for collected packages: openbabel
  Building wheel for openbabel (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/sajadahrari/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-install-3jgav96a/openbabel/setup.py'"'"'; __file__='"'"'/private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-install-3jgav96a/openbabel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-wheel-www7swdi
       cwd: /private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-install-3jgav96a/openbabel/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_ext
  Warning: invalid version number '3.1.1.1'.
  Guessing Open Babel location:
  - include_dirs: ['/Users/sajadahrari/opt/anaconda3/include/python3.8', '/usr/local/include/openbabel3']
  - library_dirs: ['/usr/local/lib']
  building 'openbabel._openbabel' extension
  swigging openbabel/openbabel-python.i to openbabel/openbabel-python_wrap.cpp
  swig -python -c++ -small -O -templatereduce -naturalvar -I/Users/sajadahrari/opt/anaconda3/include/python3.8 -I/usr/local/include/openbabel3 -o openbabel/openbabel-python_wrap.cpp openbabel/openbabel-python.i
  unable to execute 'swig': No such file or directory
  
  Error: SWIG failed. Is Open Babel installed?
  You may need to manually specify the location of Open Babel include and library directories. For example:
    python setup.py build_ext -I/usr/local/include/openbabel3 -L/usr/local/lib
    python setup.py install
  ----------------------------------------
  ERROR: Failed building wheel for openbabel
  Running setup.py clean for openbabel
Failed to build openbabel
Installing collected packages: openbabel
    Running setup.py install for openbabel ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/sajadahrari/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-install-3jgav96a/openbabel/setup.py'"'"'; __file__='"'"'/private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-install-3jgav96a/openbabel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-record-h9o3somg/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sajadahrari/opt/anaconda3/include/python3.8/openbabel
         cwd: /private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-install-3jgav96a/openbabel/
    Complete output (15 lines):
    running install
    running build_ext
    Warning: invalid version number '3.1.1.1'.
    Guessing Open Babel location:
    - include_dirs: ['/Users/sajadahrari/opt/anaconda3/include/python3.8', '/usr/local/include/openbabel3']
    - library_dirs: ['/usr/local/lib']
    building 'openbabel._openbabel' extension
    swigging openbabel/openbabel-python.i to openbabel/openbabel-python_wrap.cpp
    swig -python -c++ -small -O -templatereduce -naturalvar -I/Users/sajadahrari/opt/anaconda3/include/python3.8 -I/usr/local/include/openbabel3 -o openbabel/openbabel-python_wrap.cpp openbabel/openbabel-python.i
    unable to execute 'swig': No such file or directory
    
    Error: SWIG failed. Is Open Babel installed?
    You may need to manually specify the location of Open Babel include and library directories. For example:
      python setup.py build_ext -I/usr/local/include/openbabel3 -L/usr/local/lib
      python setup.py install
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sajadahrari/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-install-3jgav96a/openbabel/setup.py'"'"'; __file__='"'"'/private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-install-3jgav96a/openbabel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/9p/fr8j3_555dn5p5zyrwpzk5h80000gn/T/pip-record-h9o3somg/install-record.txt --single-version-externally-managed --compile --install-headers /Users/sajadahrari/opt/anaconda3/include/python3.8/openbabel Check the logs for full command output.

**Comment by jenniening** [comment]
Thanks for the update. Could you check the version of openbabel installed? Also, could you try bellow two sets of commands in python and share the outputs?

first:
from openbabel import openbabel as ob
from openbabel import pybel

second:
import openbabel as ob
import pybel

Thanks!

**Comment by Sinsilcobio** [comment]
Thank you very much for your follow-up.

Following you can find the output of all your mentioned commands.
It seems that except for "pybel", others are working fine. 

I also checked the version of openable and it is Open Babel-3.1.0.

Thank you!

**(DXGB) sajads-air:DXGB sajadahrari$ python
Python 3.8.3 (default, Jul  2 2020, 11:26:31) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from openbabel import openbabel as ob
>>> from openbabel import pybel
>>> 
>>> import openbabel as ob
>>> import pybel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pybel'
>>> 
>>> exit()
(DXGB) sajads-air:DXGB sajadahrari$ obabel
No input file or format spec or possibly a misplaced option.
Most options must come after the input files. (-i -o -O -m can be anywhwere.)

Open Babel 3.1.0 -- May  8 2020 -- 19:21:06
Usage:
obabel [-i<input-type>] <infilename> [-o<output-type>] -O<outfilename> [Options]
Try  -H option for more information.
(DXGB) sajads-air:DXGB sajadahrari$**

**Comment by Sinsilcobio** [comment]
Hello Jenniening,
I was wondering if you had a chance to look at the last post?
Thank you

**Comment by jenniening** [comment]
Hi, sorry i forgot to comment. Thanks for sharing the testing result. Yeah, actually the issue is related to openbable version, in 3.x, pybel is needed to be imported through openbable but in 2.x it can be directly imported. Please see this link for reference: https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html
One thing we can  try is instead directly  'import pybel' in script, just change that line to 'from openbabel import pybel'. Two files needed to be changed are: https://github.com/jenniening/deltaVinaXGB/blob/Light/DXGB/featureSASA.py and https://github.com/jenniening/deltaVinaXGB/blob/Light/DXGB/pharma.py. Please change the corresponding line in your local, and after making that change, please rerun the python setup.py file, the updated package should be installed again.

**Comment by Sinsilcobio** [comment]
Hi Jenniening,
Thank you very much for your help.
I belive the issue with the first test command (python run_DXGB.py --help) was resolved (see following for the out put). 
However, for the second test command (python run_DXGB.py --runfeatures --datadir ../Test_2al5 --pdbid 2al5 --average), I faced the following error. Could you please give me a clue what I am missing?

Thank you,
Sajjad

**first test command:**
(DXGB) sajads-air:DXGB sajadahrari$ python run_DXGB.py --help
Usage: run_DXGB.py [OPTIONS]

Options:
  --model TEXT        model name  [default: DXGB]
  --modeldir TEXT     absolute model directory  [default: ../Model]
  --datadir TEXT      absolute data directory  [default: ../Test]
  --pdbid TEXT        pdbid, ligand input should be pdbid_ligand.mol2 or sdf,
                      protein input should be pdbid_protein_all.pdb
  --outfile TEXT      output filename  [default: score.csv]
  --runfeatures       run features calculation  [default: False]
  --water TEXT        water type
  --opt TEXT          opt type
  --rewrite           rewrite protein part water generation, ligand
                      optimization, ligand conformation generation or not
  --average           average for 10 models
  --modelidx TEXT     model index  [default: 1]
  --featuretype TEXT  which feature will be calculated,
                      options:all,Vina,SASA,BW,Ion,dE   [default: all]
  --runrf             get deltaVinaRF20 scores
  --help              Show this message and exit.
(DXGB) sajads-air:DXGB sajadahrari$ 

**second test command:**

(DXGB) sajads-air:DXGB sajadahrari$ python run_DXGB.py --runfeatures --datadir ../Test_2al5 --pdbid 2al5 --average
pdb index: 2al5
file directory: /Users/sajadahrari/Documents/GitHub/deltaVinaXGB/Test_2al5
feature will be calculated:all
output filename : score.csv
1 molecule converted
Ligand for conformation stability:2al5_ligand.mol2
Ligand for Vina, SASA, BA, ION:2al5_ligand_rename.pdb
Protein without water molecules:2al5_protein.pdb
Protein with water molecules:2al5_protein_all.pdb
Finish Input Preparation
No Consideration of Water
No Optimized Ligand
C
Finish Vina
Finish SASA
No Ion
Finish Ion
Input Type:mol2
mol has been read
The total number of conformers before clustering: 52
The total number of conformers after clustring: 12
The lowest energy: 26.35273201345399
Input Type:mol2
Finish Feature Calculation
1
Traceback (most recent call last):
  File "run_DXGB.py", line 103, in <module>
    main()
  File "/Users/sajadahrari/opt/anaconda3/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sajadahrari/opt/anaconda3/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/sajadahrari/opt/anaconda3/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sajadahrari/opt/anaconda3/envs/DXGB/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "run_DXGB.py", line 74, in main
    test_new = run_model(inf,datadir,i,model_dir = modeldir, model_name = model, average = average, model_index = modelidx)  
  File "/Users/sajadahrari/opt/anaconda3/envs/DXGB/lib/python3.7/site-packages/DXGB-0.1.0-py3.7.egg/DXGB/run_models.py", line 37, in run_model
    mod = pickle.load(open(model_dir + "/pima.pickle_" + str(i) +  ".dat", "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sajadahrari/Documents/GitHub/deltaVinaXGB/Model/DXGB/pima.pickle_1.dat'
(DXGB) sajads-air:DXGB sajadahrari$

**Comment by Sinsilcobio** [comment]
Hi Jenniening,
The issue is resolved. There was a problem with file access and permissions.
Thank you!

**Comment by jenniening** [comment]
Thanks for updating, sounds great!
