### ISSUE TITLE
about calculating XGBscore

### ISSUE THREAD

**Issue by hfhfgo** [jenniening/deltaVinaXGB#8]
Hello Jenniening,

May I know whether I can use openbabel to transfer pdbqt files (already dock with Vina and contain 10 poses ) to the Mol2 format and rescore all the poses at the same time?

BTW, if I want to dock multiple ligands to a single protein, is there a method to rescore all the docking results

Regards,
Andy

**Comment by jenniening** [comment]
HI Andy,

Sure. You can do that using openbabel. 
We currently still need to build different folders for each protein-ligand pair, so basically just create a for loop to copy your protein to each ligand folder.

Hope this helps, thanks!

Best,
Jianing
